#!/bin/bash
# Public GitHub copy: replace this example roster or export your own
# IRREDEEMABLE_SUBJECTS before sourcing the file.
export IRREDEEMABLE_SUBJECTS="${IRREDEEMABLE_SUBJECTS:-100 101 102}"
export IRREDEEMABLE_SN_PROB_FIXED=0.15
export IRREDEEMABLE_CTRL_PROB_FIXED=0
unset IRREDEEMABLE_PT_PROB_FIXED
export IRREDEEMABLE_PT_RATIO_TARGET=1.0
export IRREDEEMABLE_PT_RATIO_MAX_CUT_FRAC=0.15
export IRREDEEMABLE_PT_RATIO_MIN_PROB=0.005
export IRREDEEMABLE_PT_RATIO_FLOOR=0.005
export IRREDEEMABLE_PT_INTERSECT_BRAINSTEM=1
export IRREDEEMABLE_PT_INTERSECT_LEAK_ONLY=1
export IRREDEEMABLE_USE_CORRECTED=1
